### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wyxuan** [QuintGao/GKCycleScrollView#12]
updateVisibleCellAppearance
NSInteger index = i % self.realCount;
当numberOfCellsInCycleScrollView返回0的时候偶发。就是0，>0反复的交替

**Comment by QuintGao** [comment]
返回0是什么操作

**Comment by wyxuan** [comment]
> 返回0是什么操作

就是没有啊

**Comment by QuintGao** [comment]
最新版已修复
