### ISSUE TITLE
如何继承GKCycleScrollViewCell

### ISSUE THREAD

**Issue by jiangqingchaoGit** [QuintGao/GKCycleScrollView#14]
继承了GKCycleScrollViewCell 项目汇报错

**Comment by QuintGao** [comment]
报什么错

**Comment by jiangqingchaoGit** [comment]
let  cell = cycleScrollView.dequeueReusableCell() as! QCCreatChallengeCell

swift:62: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by jiangqingchaoGit** [comment]
继承 你的GKCycleScrollViewCell 相当于没有进行注册。然后就会报GKCycleScrollViewCell 类型指针为空

**Comment by jiangqingchaoGit** [comment]
我必须在你定义的GKCycleScrollViewCell这个类里面进行自定义控件嘛？
因为我有多个页面将应用这套滚动效果

**Comment by QuintGao** [comment]
![WeChat2217251b2d82f15fb351962cb411c6ad](https://user-images.githubusercontent.com/13514024/121500892-4b35bd80-ca11-11eb-9e98-191efbc0ca4a.png)
这样写

**Comment by jiangqingchaoGit** [comment]
好的 谢谢
