### ISSUE TITLE
自动滚动偏差问题和defaultSelectIndex问题

### ISSUE THREAD

**Issue by EggsOfAngel** [QuintGao/GKCycleScrollView#2]
问题1
:当手指在中间view左右拖动，如果左右拖动偏移不大，这个时候没有影响。
在以下操作会出现问题：在中间view左右来回拖动，并且左右拖动偏移较大，然后在放开手指，此时自动滚动不会滚动到下一张，会滚动到下下一张。

问题2
:当设置defaultSelectIndex的时候，比如有10张图片，设置defaultSelectIndex为6，刚显示的时候没有问题，但是当计时器发生自动滚动时，并不会滚到第7页，而是会滚动到第二页。
不过如果不去设置defaultSelectIndex，而是调用scrollToCellAtIndex方法去滚动到第6页，则一切都没问题。

希望作者大神能解决一下，支持你

**Comment by EggsOfAngel** [comment]
问题1必现的情况
比如我有5张图片，GKCycleScrollView的宽度为一个屏幕，cellsize为一个屏幕的宽度减100，起始的时候，我把手指放在第一张图片，然后手指往左移动让ScrollView显示第二张，然后此时我手指依然没有离开屏幕，然后再移动回第一张，松手离开屏幕，等待定时器启动，然后，就会跳到了第三张，并没有跳到第二张
希望作者大神能解决一下

**Comment by QuintGao** [comment]
问题已修改

**Comment by EggsOfAngel** [comment]
感谢作者的辛苦解决bug，关于defaultSelectIndex问题已经ok，不过问题1依然没有解决
下面是必然出现的问题，我复述一下
我跑在iPhone11的模拟器上，GKCycleScrollView的宽度为一个屏幕，cellsize为一个屏幕的宽度减300，总共有4张图（第1，第2，第3，第4），起始的时候，我把手指放在第1张图片，然后手指往右移动让ScrollView显示前面那张，也就是第4张的时候，这个时候放手依然会连跳两张

**Comment by EggsOfAngel** [comment]
还有一个问题：
问题3:
我跑在iPhone11的模拟器上，GKCycleScrollView的宽度为一个屏幕，cellsize为一个屏幕的宽度减300，自动滚动时间为3s，总共有4张图（第1，第2，第3，第4），起始的时候，我把手指放在第1张图片，然后手指往右移动让ScrollView显示前面的前面那张，也就是第3张的时候，这个时候我先不放手，手指往左移动，当介于前面的前面那张和前面那张之间（也就是第3和第4之间），松开手，此时会回弹到前面那张（第4张），这个时候将要等6s才会滚动

**Comment by QuintGao** [comment]
你好，问题已修复
