### ISSUE TITLE
adjustCurrentCell有点问题

### ISSUE THREAD

**Issue by wenhao-fly** [QuintGao/GKCycleScrollView#25]
轮播图确实有跳页面时，卡住一半的情况 所以在viewWillAppear时加了adjustCurrentCell
没卡住一半的情况了
但手动滚动轮播图时，当前是index0，手动滑到index3，push后再返回，调用adjustCurrentCell后还是返回到index0了
这怎么解决

**Comment by QuintGao** [comment]
有demo吗，我这试了没问题

**Comment by wenhao-fly** [comment]
刚看了下代码，手动滑动轮播图时，特别右滑时，走scrollViewWillEndDragging:(UIScrollView *)scrollView withVelocity 中计算index不太准，导致timerIndex不准，所以手动滚动轮播图后timerIndex错误，导致后面的问题

**Comment by wenhao-fly** [comment]
if (horIndex <= (self.realCount - 1)) {
                        scrollView.contentOffset = CGPointMake(self.cellSize.width * (2 * self.realCount - 1), 0);
                        self.timerIndex = 2 * self.realCount
                    }
这里改成self.timerIndex = 2 * self.realCount - 1,然后scrollViewWillEndDragging中round()中改成targetContentOffset就可以了
