### ISSUE TITLE
还是adjustCurrentCell的问题

### ISSUE THREAD

**Issue by wenhao-fly** [QuintGao/GKCycleScrollView#26]
当页面轮播图有2个cell，这时是滚动的，self.timerIndex会变成3，这时刷新数据，轮播图只有一个cell了，而看了下源码self.timerIndex没有置0的地方，这时去其他页面再回来执行adjustCurrentCell，由于self.timerIndex=3，导致轮播图处一片空白。麻烦更新下代码 不然只能自己改了

**Comment by QuintGao** [comment]
欢迎提下 PR 哈

**Comment by wenhao-fly** [comment]
已提

**Comment by QuintGao** [comment]
已更新
