### ISSUE TITLE
GKCycleScrollView.m 第446 行获取出来的 cell 为 [NSNull null]

### ISSUE THREAD

**Issue by lieryang** [QuintGao/GKCycleScrollView#30]
我们的项目实际使用中有大量崩溃出现:(cell 为 null 的时候出现问题)
怀疑是这里的 index, 没有向前和向后多取一个出现的, 开发中遇到过 cell 为 null 的情况在业务侧处理了, 但是线上出现了内部崩溃问题, 太闹心了, 还有做的有开关控制,及时下线了

**Comment by lieryang** [comment]
已经提交了 fix 了 https://github.com/QuintGao/GKCycleScrollView/pull/29

**Comment by wenhao-fly** [comment]
我也偶尔会报崩溃在-[GKCycleScrollView updateVisibleCellAppearance] + 15504686803025134940
不知道是不是你说的这个

**Comment by lieryang** [comment]
先关闭了, 感谢作者!!!
